version: '2'
volumes:
    scales-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'scales-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'scales-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
  scales:
    build: ./scales
    privileged: true
    restart: always
    volumes:
        - 'scales-data:/data'
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
    labels:
      io.balena.features.balena: '1'
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
